### ISSUE TITLE
データ受け渡しの形式を決める

### ISSUE THREAD

**Issue by Chroma7p** [jphacks/B_2211#2]
## 内容

APIに関して受け渡すデータの形式を決定する

### Pros 良くなる点

データ受け渡しを円滑にする

### Cons 悪くなる点

なし

### 実現方法

対話

**Comment by Chroma7p** [comment]
```
[{
    "color": "#FFFFFF", 
    "power": 3
 },
:
:
 {
    "color": "#000000", 
    "power": 0
}]
```
みたいな感じ……?
色の受け渡し方どうしようか
Powerは3段階想定

**Comment by csenet** [comment]
@Chroma7p 
Powerって3段階に絞るのではなく、0~100とかのレンジを持たせてみるとどうですか？
ハードウェア側では極力それを実現しようとして、無理な場合は値を元に3段階に振り分けるなど。

**Comment by Chroma7p** [comment]
じゃあ0~100で
色は？？？

**Comment by csenet** [comment]
@Chroma7p 
じゃあ`#FFFFFF`みたいな形式で

**Comment by Chroma7p** [comment]
ヨシ！！
